# Numpy

Utilizando a biblioteca numpy siga as instruções abaixo:
    1 - Crie um array 6x6 preenchido com zero
    3 - Preencha o centro desse array com um array 2x2 preenchido com dois
    4 - Gere um segundo array 6x6 com números inteiros aleatórios entre 0 e 2.
    5 - Subtraia o primeiro array pelo segundo


In [1]:
import numpy as np

In [54]:

array0 = np.zeros((6, 6,))
array0




array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [86]:
array0[1:5,1:5] = np.ones(shape=(4,4))
array0
array1 = array0.copy()
array1


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [68]:
array0[2:4,2:4] = np.full([2,2],2)
array0

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 1., 0.],
       [0., 1., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [69]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [79]:
#help(np.arange)

array6 = np.random.randint(0,3,(6,6))
array6


array([[2, 1, 0, 1, 0, 2],
       [1, 0, 2, 1, 0, 0],
       [2, 1, 2, 1, 0, 0],
       [2, 0, 0, 2, 1, 1],
       [2, 2, 1, 2, 0, 0],
       [1, 2, 2, 0, 2, 2]])

In [87]:
array0 - array1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])