Numpy
1. Utilizando a biblioteca numpy siga as instruções abaixo:
   1. Crie um array 6x6 preenchido com zero
   1. Preencha o centro desse array com um array 4x4 preenchido com uns
   1. Preencha o centro desse array com um array 2x2 preenchido com dois
   1. Gere um segundo array 6x6 com números inteiros aleatórios entre 0 e 2.
   1. Subtraia o primeiro array pelo segundo

1.

1.a

In [11]:
!pip install numpy

In [12]:
import numpy as np
array1 = np.zeros((6,6))

In [13]:
array1.ndim

2

In [14]:
array1.size

36

In [15]:
array1.shape

(6, 6)

In [16]:
array1.dtype

dtype('float64')

1.b

In [33]:
# array[1]
# array1[1, 1]
# array1[1:4]
# array1[1:5]
# array1[1:-1]
# array1[1:-1, 1:-1]
# help(np.ones)
array1[1:5, 1:5] = np.ones(shape=(4,4))
array1
# não dá pra fazer assim com listas sem utilizar for

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

1.c

In [18]:
# np.array([
#   [2,2],
#   [2,2]
# ])
# np.zeros(shape=(2,2)) + 2
# np.ones(shape=(2,2)) * 2
# Não dá pra fazer assim com listas
# help(np.full)
array1[2:-2, 2:-2] = np.full(shape=(2,2), fill_value=2)
array1

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 1., 0.],
       [0., 1., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

1.d

In [19]:
# numpy random
# https://numpy.org/doc/1.16/reference/routines.random.html
# help(np.random.randint)
# np.random.randint(low=0, high=3, size=(6,6))
# numpy set seed
# https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.seed.html
np.random.seed(0)
array2 = np.random.randint(low=0, high=3, size=(6,6))
array2

array([[0, 1, 0, 1, 1, 2],
       [0, 2, 0, 0, 0, 2],
       [1, 2, 2, 0, 1, 1],
       [1, 1, 0, 1, 0, 0],
       [1, 2, 0, 2, 0, 1],
       [1, 2, 0, 1, 1, 1]])

1.e

In [20]:
array1-array2

array([[ 0., -1.,  0., -1., -1., -2.],
       [ 0., -1.,  1.,  1.,  1., -2.],
       [-1., -1.,  0.,  2.,  0., -1.],
       [-1.,  0.,  2.,  1.,  1.,  0.],
       [-1., -1.,  1., -1.,  1., -1.],
       [-1., -2.,  0., -1., -1., -1.]])


2. Crie um array de duas dimensões, no formato 9x9, com números de 0 a 80 ordenados de modo crescente e selecione:
   1. Os números ímpares
   1. Os números pares
   1. Os múltiplos de sete
   1. Os múltiplos de 10
   1. Os números 32,33,42,43

2

2.a e b

In [21]:
# help(np.arange)
# np.arange(start=0, stop=81, step=1)
array = np.arange(start=0, stop=81, step=1).reshape(9,9)
# np.arange(start=0, stop=81, step=1).reshape(9,-1)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [22]:
# array % 2
# array % 2 == 1
mask_impar = array % 2 == 1 # Mask
# mask_impar
array[mask_impar]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79])

2.b

In [23]:
# array[not mask_impar]
# array[~mask_impar]
# array % 2 == 0
mask_par = array % 2 == 0 # Mask
array[mask_par]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80])

2.c

In [24]:
array
# array % 7
# array % 7 == 0
array[array % 7 == 0]
# multi_sete = [0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77]
# numpy check array values in list
# https://numpy.org/doc/stable/reference/generated/numpy.isin.html
# mask_sete = np.isin(array, multi_sete)
# array[mask_sete]
# list(range(0, 80, 7))
# array[np.isin(array, range(0, 80, 7))]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77])

2.d

In [25]:
# numpy get matrix diagonal
# https://numpy.org/doc/stable/reference/generated/numpy.diagonal.html
# array.diagonal()
# np.diag(array)
# array[array %10 == 0]
# array.shape
# for i in range(array.shape[0]):
#   print(array[i,i])
# array.ravel()[::10]

2.e

In [26]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [27]:
# array.ravel()[[32,33,42,43]]
# array[np.isin(array, [32,33,42,43])]
array[[3,3,4,4],[5,6,6,7]]

array([32, 33, 42, 43])


3. Crie um array com três dimensões, onde a primeira dimensão são os dias da semana (seg a dom), a segunda dimensão são as semanas do mês (considere apenas 4 para todos os meses), e a terceira são os meses do ano (Jan a dezembro).
   1. Marque os finais de semana com a letra W
   1. Marque o começo do mês com a letra S
   1. Marque o final do mês com a letra E
   1. Marque os demais dias com a letra D
   1. Marque os feriados nacionais com a letra F
      - 01/01 - Ano novo
      - 15/04 - Paixão de Cristo
      - 21/04 - Tiradentes
      - 01/05 - Dia do Trabalho
      - 07/09 - Independência do Brasil
      - 12/10 - Nossa Senhora Aparecida
      - 02/11 - Finados
      - 15/11 - Proclamação da República
      - 25/12 - Natal

In [28]:
# numpy repeat array
# https://numpy.org/doc/stable/reference/generated/numpy.tile.html
month = np.arange(1,29).reshape(4,7)
# month
# np.tile(month, (12,1,1)).shape
calendar = np.tile(month, (12,1,1))
calendar

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28]],

       [[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28]],

       [[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28]],

       [[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28]],

       [[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28]],

       [[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28]],

       [[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],


3.a

In [29]:
# calendar[:,:, 5:]
# calendar[:,:, 5:] = 'W'
calendar = calendar.astype(str)
calendar[:,:, 5:] = 'W'
calendar
# Vai ter que utilizar muito for pra fazer isso em lista

array([[['1', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'W']],

       [['1', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'W']],

       [['1', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'W']],

       [['1', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'W']],

       [['1', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'W']],

       [['1', '2', '3', '

3.b

In [30]:
calendar[:, 0, 0]
calendar[:, 0, 0] = 'S'
calendar

array([[['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'W']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'W']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'W']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'W']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'W']],

       [['S', '2', '3', '

3.c

In [31]:
# calendar[:, 3, 6]
calendar[:, -1, -1]
calendar[:, -1, -1] = 'E'
calendar

array([[['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'E']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'E']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'E']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'E']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'E']],

       [['S', '2', '3', '

In [32]:
mes = [1, 4, 4, 5, 9, 10, 11, 11, 12]
dia = [1, 15, 21, 1, 7, 12, 2, 15, 25]
# dia//7
# np.array(dia)//7
# semana = np.array(dia)//7
semana = (np.array(dia)-1)//7
# (np.array(dia))%7 
dia_semana = (np.array(dia)-1)%7
# calendar[mes, semana, dia]
mes = np.array(mes) - 1
calendar[mes, semana, dia_semana] = 'F'
calendar

array([[['F', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'E']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'E']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'E']],

       [['S', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['F', '16', '17', '18', '19', 'W', 'F'],
        ['22', '23', '24', '25', '26', 'W', 'E']],

       [['F', '2', '3', '4', '5', 'W', 'W'],
        ['8', '9', '10', '11', '12', 'W', 'W'],
        ['15', '16', '17', '18', '19', 'W', 'W'],
        ['22', '23', '24', '25', '26', 'W', 'E']],

       [['S', '2', '3', '4